server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgressql://localhost:5432/authdb
    username: auth
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt:
    issuer: https://auth.vijay.local
    audience: my-rest-api
    access-token-minutes: 10
